#!/bin/bash
echo directory location: $(pwd)
echo number of files in directory: $(ls | wc -l)
echo directory last edited: $(ls -l .. | grep ${PWD##*/} | awk '{print $8}')
echo largest file/directory: $(du -a -h | sort -n | tail -n 1)
echo smallest file/directory: $(du -a -h | sort -n -r | tail -n 1)
