#!/bin/bash

declare -a loop_array

re='^[0-9]+$'

read -p "Enter a number: " num
x=0

while [[ x -le num ]]
do
	loop_array+=("$x")
	x=$((x+1))
done


for numbers in "${loop_array[@]}"
do
	if [[ $((numbers % 3)) == 0 ]]; then
		echo Fizz!
	elif [[ $((numbers % 5)) == 0 ]]; then
		echo Buzz!
	else
		echo $numbers
	fi
done	
