#!/bin/bash

declare -a loop_array

re='^[0-9]+$'

read -p "Enter a number or enter any other value to exit: " num
while [[ $num =~ $re ]] 
do
	loop_array+=($num)
	read -p "Enter a number: " num
done

for numbers in "${loop_array[@]}"
do
	if [[ $((numbers % 3)) == 0 ]]; then
		echo Fizz!
	elif [[ $((numbers % 5)) == 0 ]]; then
		echo Buzz!
	else
		echo $numbers
	fi
done	
